### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Hiuyee124** [zhenshen-mla/Series-Photo-Selection#5]
Hello,I can't open the url https://[phototriage.cs.princeton.edu](https://phototriage.cs.princeton.edu/dataset.html)/dataset.html to download the dataset. I am wondering if there is any alternative way to access the data, or if you could kindly share it with me. Thank you very much for your time and attention.

**Comment by jachinzhang1** [comment]
Hello, I cannot open the [url](http://phototriage.cs.princeton.edu/) either. As you closed this issue, could you please share the way to access the data? Thanks!
